export default function MainGiver() {
  return (
    <div className="main-giver">
      <div className="auto auto-flex">
        <div className="giver-left-wrapper">
          <div className="giver-left-up">
            <div className="together-title">
              <img src="./함께하는사람들.png" alt="" />
              <span>함께하는 사람들</span>
            </div>
            <div className="together-list">
              <ul className="carousel-track">
                <li>
                  <strong>홍00</strong>님
                </li>
                <li>
                  <strong>천00000</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>조00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>강00</strong>님
                </li>
                <li>
                  <strong>유00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>진00</strong>님
                </li>
                <li>
                  <strong>진이00000</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>조00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>진00</strong>님
                </li>
                <li>
                  <strong>한00</strong>님
                </li>
                <li>
                  <strong>강00</strong>님
                </li>
                <li>
                  <strong>진00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>이-깨끗한00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>임00</strong>님
                </li>

                <li>
                  <strong>강00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>전00</strong>님
                </li>
                <li>
                  <strong>진00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>장00</strong>님
                </li>

                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>강00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>장00</strong>님
                </li>

                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>진00</strong>님
                </li>
                <li>
                  <strong>강00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>장00</strong>님
                </li>

                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>88000</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>장00</strong>님
                </li>

                <li>
                  <strong>장00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>백00</strong>님
                </li>
                <li>
                  <strong>경000000000</strong>님
                </li>
                <li>
                  <strong>진00</strong>님
                </li>
                <li>
                  <strong>장00</strong>님
                </li>
                <li>
                  <strong>이00000</strong>님
                </li>

                <li>
                  <strong>백00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>신00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>최00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>박00</strong>님
                </li>
                <li>
                  <strong>홍00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>최00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>전00</strong>님
                </li>
                <li>
                  <strong>조00</strong>님
                </li>

                <li>
                  <strong>박00</strong>님
                </li>
                <li>
                  <strong>고00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>표00</strong>님
                </li>
                <li>
                  <strong>박00</strong>님
                </li>
                <li>
                  <strong>최00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>석00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>정00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>고00</strong>님
                </li>
                <li>
                  <strong>심00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>안00</strong>님
                </li>
                <li>
                  <strong>한00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>명00</strong>님
                </li>
                <li>
                  <strong>박00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>구00</strong>님
                </li>
                <li>
                  <strong>권00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>한0</strong>님
                </li>

                <li>
                  <strong>고00</strong>님
                </li>
                <li>
                  <strong>황00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>장00</strong>님
                </li>

                <li>
                  <strong>백00</strong>님
                </li>
                <li>
                  <strong>전00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>최00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>남00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>강00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>최00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>박00</strong>님
                </li>
                <li>
                  <strong>홍00</strong>님
                </li>
                <li>
                  <strong>신00</strong>님
                </li>
                <li>
                  <strong>서00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>전00</strong>님
                </li>
                <li>
                  <strong>황00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>전00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>오00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
                <li>
                  <strong>이00</strong>님
                </li>
                <li>
                  <strong>김00</strong>님
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="giver-right-wrapper">
          <div className="giver-right-up">
            <div className="welfare-ask">
              <ul>
                <li>
                  <span style={{ color: '#fff' }}>복지관문의</span>
                </li>
                <li>
                  <img src="./전화기.png" alt="" />
                  <span style={{ color: '#fff260', fontWeight: '700' }}>031-846-7003</span>
                </li>
                <li>
                  <i className="bx bx-time-five"></i>
                  <span style={{ color: '#fff' }}>09:00 ~ 18:00 (주말, 공휴일 제외)</span>
                </li>
              </ul>
            </div>
          </div>

          <div className="giver-right-down"></div>
        </div>
      </div>
    </div>
  );
}
